// src/generator.ts
import fs from 'fs';
import path from 'path';
import { glob } from 'glob';

interface GeneratorOptions {
  pagesDir: string;
  outputFile: string;
}

const lazyImport = (componentName: string, filePath: string, outputFile: string) => {
  const relativePath = path.relative(path.dirname(outputFile), filePath).replace(/\\/g, '/');
  return `const ${componentName} = lazy(() => import('./${relativePath}'));`;
};

// 👇 FUNÇÃO CORRIGIDA 👇
function formatRoutePath(filePath: string, pagesDir: string): string {
  const relativePath = path.relative(pagesDir, filePath);

  const routePath = relativePath
    .replace(/\\/g, '/')
    .replace(/\.(tsx|jsx)$/, '')
    .replace(/\/index$/, '')
    .replace(/^index$/, '')
    .replace(/\[\.\.\.([^\]]+)\]/g, '*')
    .replace(/\[([^\]]+)\]/g, ':$1');

  return `/${routePath}`;
}


export async function generateRoutes(options: GeneratorOptions) {
  const { pagesDir, outputFile } = options;
  console.log('🔄 [vite-react-file-router] Gerando rotas...');
  
  const pageFiles = await glob('**/*.{tsx,jsx}', {
    cwd: pagesDir,
    absolute: true,
  });

  const imports: string[] = [];
  const routeElements: string[] = [];

  pageFiles.forEach((file, index) => {
    const componentName = `Page${index}`;
    imports.push(lazyImport(componentName, file, outputFile));
    routeElements.push(
      `<Route path="${formatRoutePath(file, pagesDir)}" element={<${componentName} />} />`
    );
  });
  
  routeElements.sort((a, b) => {
    if (a.includes('*')) return 1;
    if (b.includes('*')) return -1;
    return b.length - a.length;
  });

  const outputContent = `
// ATTENTION: This file is automatically generated by vite-react-file-router.
// Do not edit manually.
import React, { lazy, Suspense } from 'react';
import { Routes, Route } from 'react-router-dom';

${imports.join('\n')}

const LoadingComponent = () => null;

export const AppRoutes = () => (
  <Suspense fallback={<LoadingComponent />}>
    <Routes>
      ${routeElements.join('\n      ')}
    </Routes>
  </Suspense>
);
  `;

  fs.mkdirSync(path.dirname(outputFile), { recursive: true });
  fs.writeFileSync(outputFile, outputContent.trim());
  console.log(`✅ [vite-react-file-router] Rotas geradas com sucesso!`);
}