// src/generator.ts
import fs from 'fs';
import path from 'path';
import { glob } from 'glob';

// 👇 1. ADICIONE A NOVA OPÇÃO AQUI
interface GeneratorOptions {
  pagesDir: string;
  outputFile: string;
  importSource: string; // Recebe a nova opção
}

// ... (as funções lazyImport e formatRoutePath não mudam) ...
const lazyImport = (componentName: string, filePath: string, outputFile: string) => {
  const relativePath = path.relative(path.dirname(outputFile), filePath).replace(/\\/g, '/');
  return `const ${componentName} = lazy(() => import('./${relativePath}'));`;
};

function formatRoutePath(filePath: string, pagesDir: string): string {
  const relativePath = path.relative(pagesDir, filePath);
  const routePath = relativePath
    .replace(/\\/g, '/')
    .replace(/\.(tsx|jsx)$/, '')
    .replace(/\/index$/, '')
    .replace(/^index$/, '')
    .replace(/\[\.\.\.([^\]]+)\]/g, '*')
    .replace(/\[([^\]]+)\]/g, ':$1');
  return `/${routePath}`;
}

// 👇 2. RECEBA A OPÇÃO NOS PARÂMETROS DA FUNÇÃO
export async function generateRoutes(options: GeneratorOptions) {
  const { pagesDir, outputFile, importSource } = options;
  console.log('🔄 [react-router-file] Gerando rotas...');
  
  const pageFiles = await glob('**/*.{tsx,jsx}', {
    cwd: pagesDir,
    absolute: true,
  });

  const imports: string[] = [];
  const routeElements: string[] = [];

  pageFiles.forEach((file, index) => {
    const componentName = `Page${index}`;
    imports.push(lazyImport(componentName, file, outputFile));
    routeElements.push(
      `<Route path="${formatRoutePath(file, pagesDir)}" element={<${componentName} />} />`
    );
  });
  
  routeElements.sort((a, b) => {
    if (a.includes('*')) return 1;
    if (b.includes('*')) return -1;
    return b.length - a.length;
  });

  const outputContent = `
// ATTENTION: This file is automatically generated by react-router-file.
// Do not edit manually.
import { lazy, Suspense } from 'react';
import { Routes, Route } from '${importSource}';

${imports.join('\n')}

const LoadingComponent = () => null;

export const AppRoutes = () => (
  <Suspense fallback={<LoadingComponent />}>
    <Routes>
      ${routeElements.join('\n      ')}
    </Routes>
  </Suspense>
);
  `;

  fs.mkdirSync(path.dirname(outputFile), { recursive: true });
  fs.writeFileSync(outputFile, outputContent.trim());
  console.log(`✅ [react-router-file] Rotas geradas com sucesso!`);
}